import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { Bridge } from '../bridge.js';
import { parseTime, formatTime } from '../timeparse.js';
import { parseTranscript, formatTranscript, searchTranscript } from '../transcript.js';
import type { Segment } from '../transcript.js';
import { fetchCaptions } from '../captions.js';
import { fetchChapters } from '../chapters.js';
import { ok, handler, resolveVideoTarget } from './util.js';

interface CachedTranscript {
  title: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
}

// Process-lifetime cache: transcripts don't change, and search/re-reads shouldn't refetch.
const cache = new Map<string, CachedTranscript>();

/**
 * Fetch (or reuse) the transcript of a video. Captions come from YouTube directly rather
 * than from the page, so any video can be read — `video` accepts a URL or id for a video
 * that was never opened, and omitting it falls back to whatever is in the managed tab.
 */
async function resolveTranscript(
  bridge: Bridge,
  video?: string,
  lang?: string,
): Promise<CachedTranscript> {
  const target = await resolveVideoTarget(bridge, video);
  const key = `${target.videoId}:${lang ?? ''}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const payload = await fetchCaptions(target.videoId, lang);
  const segments = parseTranscript(payload.raw);
  if (segments.length === 0)
    throw new Error('The transcript for this video is empty — it may have no usable captions.');
  const entry: CachedTranscript = {
    title: target.title || payload.title,
    language: payload.language,
    isAutoGenerated: payload.isAutoGenerated,
    segments,
  };
  cache.set(key, entry);
  return entry;
}

export function registerTranscriptTools(server: McpServer, bridge: Bridge): void {
  server.registerTool(
    'get_transcript',
    {
      description:
        'Get a video\'s caption transcript as "[m:ss] text" lines. Reads any video without ' +
        'opening or playing it — pass a URL or id to study a video you never intend to watch. ' +
        'Long transcripts are truncated — pass start/end to window a range, or use search_transcript to find a topic.',
      inputSchema: {
        start: z.string().optional().describe('Window start, e.g. "1:30" — omit for the beginning'),
        end: z.string().optional().describe('Window end, e.g. "12:00" — omit for the end'),
        lang: z
          .string()
          .optional()
          .describe('Language code like "en" — omit for the default track'),
        video: z
          .string()
          .optional()
          .describe('Video URL, id, or saved title — omit for the currently open video'),
      },
    },
    handler(async ({ start, end, lang, video }) => {
      const startS = start === undefined ? undefined : parseTime(start);
      const endS = end === undefined ? undefined : parseTime(end);
      if (startS !== undefined && endS !== undefined && endS <= startS)
        throw new Error(`end (${formatTime(endS)}) must be after start (${formatTime(startS)})`);
      const t = await resolveTranscript(bridge, video, lang);
      const header = `Transcript of "${t.title}" (${t.language}${t.isAutoGenerated ? ', auto-generated' : ''}):`;
      return ok(`${header}\n\n${formatTranscript(t.segments, { start: startS, end: endS })}`);
    }),
  );

  server.registerTool(
    'search_transcript',
    {
      description:
        "Search a video's transcript for a word or phrase (case-insensitive). Works on any " +
        'video without opening it — pass a URL or id. Returns matching moments with timestamps ' +
        'and surrounding context — pair with seek to jump to a topic.',
      inputSchema: {
        query: z.string().describe('Word or phrase to find, e.g. "dorian mode"'),
        lang: z
          .string()
          .optional()
          .describe('Language code like "en" — omit for the default track'),
        video: z
          .string()
          .optional()
          .describe('Video URL, id, or saved title — omit for the currently open video'),
      },
    },
    handler(async ({ query, lang, video }) => {
      const t = await resolveTranscript(bridge, video, lang);
      const matches = searchTranscript(t.segments, query);
      if (matches.length === 0) return ok(`No transcript matches for "${query}" in "${t.title}".`);
      return ok({
        video: t.title,
        matches: matches.map((m) => ({ time: formatTime(m.start), context: m.context })),
      });
    }),
  );

  server.registerTool(
    'get_chapters',
    {
      description:
        "Get a video's chapter markers — the author's own outline of its structure, which is " +
        'the cheapest way to understand a long video before reading its transcript. Each chapter ' +
        'start feeds straight into seek or loop_section. Works on any video without opening it. ' +
        'Many videos have no chapters; that is a normal empty result, not an error.',
      inputSchema: {
        video: z
          .string()
          .optional()
          .describe('Video URL, id, or saved title — omit for the currently open video'),
      },
    },
    handler(async ({ video }) => {
      const target = await resolveVideoTarget(bridge, video);
      const result = await fetchChapters(target.videoId);
      const chapters = result.chapters;
      const name = target.title || result.title;
      if (chapters.length === 0)
        return ok(
          `"${name}" has no chapter markers. Use get_transcript or search_transcript to explore it instead.`,
        );
      return ok({
        video: name,
        chapters: chapters.map((c) => ({ time: formatTime(c.start), title: c.title })),
      });
    }),
  );
}
