// Fetches caption data straight from YouTube. The web player's caption URLs are
// gated behind proof-of-origin tokens (they answer 200 with an empty body) and the
// innertube get_transcript endpoint returns FAILED_PRECONDITION for every client,
// but the /player response for the ANDROID innertube client still hands out caption
// URLs that work without a POT token — from any process, no browser context needed.

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // 'asr' = auto-generated
}

export interface CaptionPayload {
  language: string;
  isAutoGenerated: boolean;
  /** timedtext json3 payload — feed to parseTranscript */
  raw: unknown;
}

const ANDROID_CLIENT = {
  clientName: 'ANDROID',
  clientVersion: '20.10.38',
  androidSdkVersion: 30,
  hl: 'en',
  gl: 'US',
};
const ANDROID_UA = 'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip';
const FETCH_TIMEOUT_MS = 15_000;

export function pickTrack(tracks: CaptionTrack[], lang?: string): CaptionTrack {
  if (lang) {
    const exact = tracks.filter(
      (t) => t.languageCode === lang || t.languageCode.startsWith(`${lang}-`),
    );
    if (exact.length === 0) {
      const available = tracks
        .map((t) => t.languageCode + (t.kind === 'asr' ? ' (auto)' : ''))
        .join(', ');
      throw new Error(`No "${lang}" caption track. Available: ${available}`);
    }
    return exact.find((t) => t.kind !== 'asr') ?? exact[0];
  }
  const manual = tracks.filter((t) => t.kind !== 'asr');
  const english = (arr: CaptionTrack[]) => arr.find((t) => t.languageCode?.startsWith('en'));
  return english(manual) ?? manual[0] ?? english(tracks) ?? tracks[0];
}

export async function fetchCaptions(videoId: string, lang?: string): Promise<CaptionPayload> {
  const res = await fetch('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'user-agent': ANDROID_UA },
    body: JSON.stringify({ context: { client: ANDROID_CLIENT }, videoId }),
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!res.ok) throw new Error(`YouTube player request failed: HTTP ${res.status}`);
  const data = (await res.json()) as any;
  const status = data?.playabilityStatus?.status;
  if (status && status !== 'OK') {
    const reason = data.playabilityStatus?.reason;
    throw new Error(`Cannot fetch captions — video is ${status}${reason ? `: ${reason}` : ''}`);
  }
  const tracks: CaptionTrack[] =
    data?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (tracks.length === 0) throw new Error('This video has no captions available.');
  const track = pickTrack(tracks, lang);
  const url = new URL(track.baseUrl);
  url.searchParams.set('fmt', 'json3');
  const capRes = await fetch(url, {
    headers: { 'user-agent': ANDROID_UA },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  const text = await capRes.text();
  if (!capRes.ok || !text)
    throw new Error(`Caption download failed: HTTP ${capRes.status}, ${text.length} bytes`);
  return {
    language: track.languageCode,
    isAutoGenerated: track.kind === 'asr',
    raw: JSON.parse(text),
  };
}
